Add OpenAI API call with node.js
molxno/astro-pm-extension pull request #2
Opened 2024-08-10 15:54 UTC by molxno

### Milestone
Fix OpenAI API to use .env and node.js library.

2024-08-10 16:11 UTC, SrRiuz requested changes

2024-08-10 16:11 UTC, SrRiuz commented on src/pages/content/hooks/useGpt.tsx
> +            console.log("Mapped prompt:", PROMPT);
Remove "console.log"

2024-08-10 16:11 UTC, SrRiuz commented on src/pages/content/components/FloatingMenu/Menu.tsx
> +                                    text: text,
Change indentation to 2

2024-08-10 16:17 UTC, SrRiuz reviewed
Remove the "gtp_api_key" property in the settings file

2024-08-11 02:18 UTC, molxno commented on src/pages/content/components/FloatingMenu/Menu.tsx
> +                                    text: text,
We do this when choosing the code formatter, so we fix this kind of details.

2024-08-12 22:24 UTC, merged